// flow-typed signature: 48c131587aa61788dc1625ad1ad4a7a7
// flow-typed version: <<STUB>>/opencv_v^6.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opencv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opencv' {
  declare module.exports: any;
  declare type Matrix;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opencv/examples/addweighted' {
  declare module.exports: any;
}

declare module 'opencv/examples/camera' {
  declare module.exports: any;
}

declare module 'opencv/examples/car-detection' {
  declare module.exports: any;
}

declare module 'opencv/examples/color-filter' {
  declare module.exports: any;
}

declare module 'opencv/examples/contours' {
  declare module.exports: any;
}

declare module 'opencv/examples/convert-image' {
  declare module.exports: any;
}

declare module 'opencv/examples/detect-shapes' {
  declare module.exports: any;
}

declare module 'opencv/examples/dissimilarity' {
  declare module.exports: any;
}

declare module 'opencv/examples/face-detection-rectangle' {
  declare module.exports: any;
}

declare module 'opencv/examples/face-detection' {
  declare module.exports: any;
}

declare module 'opencv/examples/face-proxy' {
  declare module.exports: any;
}

declare module 'opencv/examples/mat-normalize' {
  declare module.exports: any;
}

declare module 'opencv/examples/mat-put' {
  declare module.exports: any;
}

declare module 'opencv/examples/motion-track' {
  declare module.exports: any;
}

declare module 'opencv/examples/quad-crosses' {
  declare module.exports: any;
}

declare module 'opencv/examples/remove-lines' {
  declare module.exports: any;
}

declare module 'opencv/examples/salt' {
  declare module.exports: any;
}

declare module 'opencv/examples/take-face-pics' {
  declare module.exports: any;
}

declare module 'opencv/examples/test' {
  declare module.exports: any;
}

declare module 'opencv/examples/warp-image' {
  declare module.exports: any;
}

declare module 'opencv/include_dirs' {
  declare module.exports: any;
}

declare module 'opencv/lib/bindings' {
  declare module.exports: any;
}

declare module 'opencv/lib/opencv' {
  declare module.exports: any;
}

declare module 'opencv/smoke/smoketest' {
  declare module.exports: any;
}

declare module 'opencv/test/examples' {
  declare module.exports: any;
}

declare module 'opencv/test/unit' {
  declare module.exports: any;
}

declare module 'opencv/utils/find-opencv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opencv/examples/addweighted.js' {
  declare module.exports: $Exports<'opencv/examples/addweighted'>;
}
declare module 'opencv/examples/camera.js' {
  declare module.exports: $Exports<'opencv/examples/camera'>;
}
declare module 'opencv/examples/car-detection.js' {
  declare module.exports: $Exports<'opencv/examples/car-detection'>;
}
declare module 'opencv/examples/color-filter.js' {
  declare module.exports: $Exports<'opencv/examples/color-filter'>;
}
declare module 'opencv/examples/contours.js' {
  declare module.exports: $Exports<'opencv/examples/contours'>;
}
declare module 'opencv/examples/convert-image.js' {
  declare module.exports: $Exports<'opencv/examples/convert-image'>;
}
declare module 'opencv/examples/detect-shapes.js' {
  declare module.exports: $Exports<'opencv/examples/detect-shapes'>;
}
declare module 'opencv/examples/dissimilarity.js' {
  declare module.exports: $Exports<'opencv/examples/dissimilarity'>;
}
declare module 'opencv/examples/face-detection-rectangle.js' {
  declare module.exports: $Exports<'opencv/examples/face-detection-rectangle'>;
}
declare module 'opencv/examples/face-detection.js' {
  declare module.exports: $Exports<'opencv/examples/face-detection'>;
}
declare module 'opencv/examples/face-proxy.js' {
  declare module.exports: $Exports<'opencv/examples/face-proxy'>;
}
declare module 'opencv/examples/mat-normalize.js' {
  declare module.exports: $Exports<'opencv/examples/mat-normalize'>;
}
declare module 'opencv/examples/mat-put.js' {
  declare module.exports: $Exports<'opencv/examples/mat-put'>;
}
declare module 'opencv/examples/motion-track.js' {
  declare module.exports: $Exports<'opencv/examples/motion-track'>;
}
declare module 'opencv/examples/quad-crosses.js' {
  declare module.exports: $Exports<'opencv/examples/quad-crosses'>;
}
declare module 'opencv/examples/remove-lines.js' {
  declare module.exports: $Exports<'opencv/examples/remove-lines'>;
}
declare module 'opencv/examples/salt.js' {
  declare module.exports: $Exports<'opencv/examples/salt'>;
}
declare module 'opencv/examples/take-face-pics.js' {
  declare module.exports: $Exports<'opencv/examples/take-face-pics'>;
}
declare module 'opencv/examples/test.js' {
  declare module.exports: $Exports<'opencv/examples/test'>;
}
declare module 'opencv/examples/warp-image.js' {
  declare module.exports: $Exports<'opencv/examples/warp-image'>;
}
declare module 'opencv/include_dirs.js' {
  declare module.exports: $Exports<'opencv/include_dirs'>;
}
declare module 'opencv/lib/bindings.js' {
  declare module.exports: $Exports<'opencv/lib/bindings'>;
}
declare module 'opencv/lib/opencv.js' {
  declare module.exports: $Exports<'opencv/lib/opencv'>;
}
declare module 'opencv/smoke/smoketest.js' {
  declare module.exports: $Exports<'opencv/smoke/smoketest'>;
}
declare module 'opencv/test/examples.js' {
  declare module.exports: $Exports<'opencv/test/examples'>;
}
declare module 'opencv/test/unit.js' {
  declare module.exports: $Exports<'opencv/test/unit'>;
}
declare module 'opencv/utils/find-opencv.js' {
  declare module.exports: $Exports<'opencv/utils/find-opencv'>;
}
