// flow-typed signature: 405a7e1d9a43ac2654080abe7440977c
// flow-typed version: <<STUB>>/robotjs_v^0.4.7/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'robotjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'robotjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'robotjs/test/all' {
  declare module.exports: any;
}

declare module 'robotjs/test/bitmap' {
  declare module.exports: any;
}

declare module 'robotjs/test/keyboard' {
  declare module.exports: any;
}

declare module 'robotjs/test/mouse' {
  declare module.exports: any;
}

declare module 'robotjs/test/screen' {
  declare module.exports: any;
}

// Filename aliases
declare module 'robotjs/index' {
  declare module.exports: $Exports<'robotjs'>;
}
declare module 'robotjs/index.js' {
  declare module.exports: $Exports<'robotjs'>;
}
declare module 'robotjs/test/all.js' {
  declare module.exports: $Exports<'robotjs/test/all'>;
}
declare module 'robotjs/test/bitmap.js' {
  declare module.exports: $Exports<'robotjs/test/bitmap'>;
}
declare module 'robotjs/test/keyboard.js' {
  declare module.exports: $Exports<'robotjs/test/keyboard'>;
}
declare module 'robotjs/test/mouse.js' {
  declare module.exports: $Exports<'robotjs/test/mouse'>;
}
declare module 'robotjs/test/screen.js' {
  declare module.exports: $Exports<'robotjs/test/screen'>;
}
